<?php include("includes/header.php")?>
<div class="content">
	<div class="what-we-do-content">
		<h2><a href="#">Inbound support</a></h2>
		<div>
			<p>
				We provide multilingual services for customer assistance, which facilitates in customer satisfaction. We help clients address customer service across various delivery channels.
			</p>
			<p>
				We are customised to meet unique requirements of the clients.Innovative technology is used to provide state-of-the-art software maintenance and system troubleshooting meant for supporting the customers. We impliments Tier level supports for Technical maintenece and troubleshooting to ensure the best service is available and continously monitored by domain experts.
			</p>

			<p>
				Customer Queries, complaints and customization requests with solutions provided are effectivitly maintained as a solution repository which will be considered for an internal discussion with clients , considering the current trend and such for a sound business. Hence our services extend the opportunity to try out something new, something that has not been experimented in the past.
			</p>
		</div>

		<h2><a href="#">Technical Help Desk</a></h2>
		<div>
			<p>
				We provide excellent and quality technical support to organizations globally with fine combination of Domain Knowledge and Experts resulting in flawless technical resolutions, We provide selected hour or 24/7 supports
			</p>
		</div>

		<h2><a href="#">Customer Care</a></h2>
		<div>
			<p>
				Our Executives are trained to deal effectively with varied customer problems within the assigned turn around time. We have redifined call processing and telecom equipment where customer centric operations are adeptly performed. Our call routing ensures there is high availablilty of the executive to serve the customers request.We not only provide qualitative cost effective customer care, but also maximize the value generated by every customer touch-point.
			</p>
		</div>

		<h2><a href="#">24/7 support</a></h2>
		<div>
			<p>
				We not only provide qualitative cost effective customer care, but also maximize the value generated by every customer touch-point. This round the clock support encourages transparent escalation of an issue through our executives and engineers.The ultimate goal of this process is to ensure the clients promises are met.
			</p>
		</div>
	</div>
	
	<script type="text/javascript">
		$(function() {
			$(".what-we-do-content").accordion({ icons: 
													{ "header": "acc-ui-icon-header", "headerSelected": "acc-ui-icon-header-selected" } }, 
													{ "clearStyle": true }
												 );
		});
	</script>
</div>
<?php include("includes/footer.php")?>